//------ products ----------------
GET https://xamen-api.vercel.app/product/getAll

###

GET https://xamen-api.vercel.app/product/getById/637b3da7fb2b329daeb80858
###

GET https://xamen-api.vercel.app/product/getBySlug/veranda-blend
###


// --------------------------------------------------


//---------- category ----------
POST https://xamen-api.vercel.app/category/getByCategoryId
Content-Type: application/json

{
    "categoryId": ["dark-roast", "decaf-coffee"]
}

###

GET https://xamen-api.vercel.app/category/getById/decaf-coffee


###

GET https://xamen-api.vercel.app/category/getAll

###
// --------------------------------------------------

// --------------------- user ---------------------
// GET

GET https://xamen-api.vercel.app/user/getALl
###



###
PUT https://xamen-api.vercel.app/user/changePassword
Content-Type: application/json

{
    "_id": "6368c01c7f52287b1c68fce1",
    "oldPassword": "4321",
    "newPassword": "1234"
}

###
DELETE https://xamen-api.vercel.app/user/delete/636772b443cb7f4b386d85c7


// --------------------------------------------------


// ---------------------- ORDER -----------------
###

//Post
POST https://xamen-api.vercel.app/order/create
Content-Type: application/json

{
        "customer":  {
            "_id":"6368c01c7f52287b1c68fce1",
            "address": ,
            
  
        },
        "delivery":{
            "shipping": ,
            "status": 
        },
        "item": [
            { 
                "_id": "63515da230fedc22b41e69c4",
                "qty": 1 ,
                "price": 123,
                
            }
            
        ]
}
###


// --------------------------------------------------


// ---------------------- CART -----------------

PUT https://xamen-api.vercel.app/user/test/63a81e3af2b737707a9cff49
Content-Type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTgxZTNhZjJiNzM3NzA3YTljZmY0OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzE5NjY1MTIsImV4cCI6MTY3MjIyNTcxMn0.Bd2kOr_jt0J_vYOhkyt4Toxncl0JvFtVI6tX9GF_pl0

{
    "mail": "fred@xdssdsses.se",
    "oldPassword": "1234",
    "newPassword": "4321"
}
###


// LOGGIN USER
POST https://xamen-api.vercel.app/user/login
Content-Type: application/json

{
    "mail": "fred@mail.se",
    "password": "1234"
}


###

//REGISTER USER
POST https://xamen-api.vercel.app/auth/register
Content-Type: application/json

{
    "firstName": "fred",
    "lastName": "x",
    "mail": "fred@mail.se",
    "password": "1234",
    "address": "gatan",
    "zip": 43439
}

###
//Check cookie token 
POST https://xamen-api.vercel.app/auth/cookie
Accept: "applicaiton/json"
Content-Type: "application/json"
withCredentials: "true"
credentials: "include" 

{
    "firstName": "fred"
}